name: Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AshrafulAbedin
          outputs: |
            dist/snake-dark.svg?color_snake=f59e0b&color_dots=0a0805,2a1a06,5c3a0a,a06010,d97706&color_empty=0a0805
            dist/snake-light.svg?color_snake=f59e0b&color_dots=f5f0e8,e8d5a3,c9a55a,a07010,d97706&color_empty=f5f0e8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: update snake [skip ci]"
          branch: main
